# Site settings
name: A Share Place
email: Stone6762@qq.com
author: FanLaoShi
url: https://github.com/crazymonkey6762/
resume_site: https://crazymonkey6762.github.io/
github: https://github.com/crazymonkey6762/
baseurl: 
description: Actually, less is more!
meta_description: 范威振;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: crazymonkey6762
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : Stone6762
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light